# Use the official Nginx base image
FROM nginx:latest

# Copy custom HTML file to Nginx document root
COPY index.html /usr/share/nginx/html

# Expose the port the app runs on
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"] 
